CREATE TABLE [dbo].[User]
(
    --[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Id] NVARCHAR(128) NOT NULL PRIMARY KEY,
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [EmailAddress] NVARCHAR(256) NOT NULL,
    [CreatedDate] DATETIME2 NOT NULL DEFAULT getutcdate()
)
